### ISSUE TITLE
No helpfull (((

### ISSUE THREAD

**Issue by lbatl** [NelloKudo/Apple-Mobile-Drivers-Installer#2]
Still not working. reboot no sense, unknown device at iPad on Windows 11

**Comment by NelloKudo** [comment]
That sounds like a cable issue, sometimes some cables are just not recognized from trasmitting data. Have you tried installing iTunes and checking if Windows Update pulls anything?

**Comment by lbatl** [comment]
> That sounds like a cable issue, sometimes some cables are just not recognized from trasmitting data. Have you tried installing iTunes and checking if Windows Update pulls anything?

dunno, after some 20 reconnections was done in iTunes, strange problem
